language: java
jdk: openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
- postgresql
before_script:
- psql -c 'create database POSTGRESQL;' -U postgres
addons:
  sonarcloud:
    organization: climatetree
    token:
      secure: d84AOZxqMDnUMkhEEVSS9M01tF6j2GzI4de/nMBQqha9Za3b5csk63y6fUJCjeDAGCJ4O68EzGiEEztVjd+Rl/Hiz4hN7KP2aiAMk2cPGSpWSlnCyzgL/bzgiYCUHV2It68oDCCv2v3ZuBNneIiVsmS/Alk7pzWQlfmVBXkuhPN0JCezFx4x+uvJgyZKThcJlIXQ0g9Gk/EWx7EnbwDHLFoHkvb7WQF6VfjLDgwU5bk+10kqxqOcnEfNb2YRQCy+B5Rn+lxrbv6AeWVwHHnQZ7/SrantEdOnjySPEYV2WmbLD+zeJnNl6/lPjtkG97ksktbzT5iKvmqs3hhuAwNGYzi8QwlWlJSZIHiLzX63tKwJTFpinGsbVCmhOdokZc0gy1byjRAU9VBQBMiYHBA4Qrd8gkkxkdeLvWI3UeVmTDQ+9H6gn4FY2Ai5EaCoSF7rXBXClSO3A7YRcMDwTPe9pfTtKK2DVjVkvDKZQUCKE5FWdH8ob+FRTjNIAwp5K89EMj4SbJ0qnqHBIQgcqhVLFhlYfTBhbBzlw9gb6HIHC8GRgiad65gKHWBm0mvFZEfSijdPnaWp2rnMeB340ZHMARQ1Jcl27cg6rInXKpDP+VU33+gUSTViGuohmpcBscqXoQS5rnxBR7MTNV89Itew1IqQiMjb42j6DPU4qcQYUOM=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=com.climatetree:user-microservice
deploy:
  provider: script
  script: bash ./docker_push.sh
  on:
    branch: master
notifications:
  slack:
    secure: Jp+R1MGFliTq9KoPA1du+dqVyb8WxjzZA6xybS28bZKavZSfthfMyFjH7KwbNxyrnnKHLLhYiBcw6UMaHYzJurZZ/tLgz+O+BvzuBbCJFBiqcVFXfMkPePj0P3Z3bQW/bJu4a1N53BoVI32XqVggariD5vxhuhYqwNKgGDAiFckfee/bW52LXg9sXEMiHMehOoKhGsz3Nnpy//oi7A1fKGvfmHekBsf37C1Rl86x4nypIBWvBbuiXqzVgxMja1z6xekynVLnQj635akd1giuOCb59+Ljna41+7LEnFpFDGZn372c0/ZVGAht1fTYbrWCoxU88eAA/UQj09xZ00jffKVR0VQrQ6/Y1eZACH1cLvBr2ad7SsjnpGJHThlJ7bY5xb4HyW+fEUswHG72Sh9tZKAeqVKd48kACtuNQj/SvVNaocQcxBAOmla6/htpHQBwabjGbf7btSQ5y1B4qSaf0tvgdsufddruiZRdQBvaqxM7L3RtrFUzIpwEhjJCdknUGRtvN+aSGWakdHbPdFp8ilsRLaQxr299C8NYOzqiWzyr0ZV6A8R3JWLHQkgor8yWMnoinGD7wU23RYLwF97g3G37tVs0aNN81CZvS/SbCzHDPrkIf1nv1PlRFKp1dkWR+zSDyowDAsw6uSjRuBsQpBw9Iou/zprKs2uQEtnc05k=
    on_success: never
    on_failure: always
env:
  global:
    secure: ES5rHqVOk1TecWaWmK2i7V/CwrhQSNfAakaSdz0e9y7f9YhY4Akcnk4kOPutwU1XtUS/IZuTsPlGW/P0H0MicItZgofU7DIBCbmSUuAS6GMCTpq9Q/Du63E+scVmS9vDvSyxqlVd96H8VoDovAPdageDSwigNViIPz6Sstjyerzcb3rxyHr1I1JbP8COQkpWkTqyt1h+u99k6LoCcsbxNnSjx3IldGM2MoS1LhOF9PdD79NFbgyDad/mlD7mBofy+lUY6yokBX2CzXVFIrWd51B+YkfNwmp+xHB3rC3kL1f+TSN7Y57Q5ZzUFB9Vr5225F+7sLVO+OD9b5wv0csdsco930k6LuFF9So1aFihNw2WbiYwmOCYL7hTb7Otp1t0Ay/qANvJlj8Kxexa9J2rBVWeu5hv3BIWgKmPUO7DBT+PsQgQYIBZiOfP9FwuRSZr4QdIRFaJBHmWk3w+DGw8gRO4AnCxlB8oWZ1mfAnOshvNURsRUJkBsQ4k64ERm0L8EWzY9Uxg5NN4IVS71tyI+KF/cY+9oe3V4+DFHnZ4BoBTeqPvDvo9ucWmMdsKAxHiJTXWZ0xOs4X0GvEYsOvuVXxsx6jBdXi1GkvuTmowfRzx+SLz/vVlskENSfuj2Ky49uZgmlb++PD9y8um38IT6QB98GEGezdc1OFNeG2Zg4M=
